### ISSUE TITLE
Instamojo-OpenCart-2.3.X

### ISSUE THREAD

**Issue by kapeel45** [Instamojo/Instamojo-OpenCart-2.0#10]
When can be new extension code available for opencart 2.3 where in every files are added in extension folder. May be there would be some path issue and new variables added.

**Comment by ashwch** [comment]
We will go through the changes introduced in 2.3 and will release/upgrade the package accordingly.

**Comment by ashwch** [comment]
@kapeel45 Plugin for 2.3.0.2 is out: https://github.com/Instamojo/Instamojo-Opencart-2.3.X
